apiVersion: v1
kind: Service
metadata:
  name: antifausa-net
spec:
  selector:
    app: antifausa-net
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: antifausa-net
spec:
  selector:
    matchLabels:
      app: antifausa-net
  replicas: 3
  template:
    metadata:
      labels:
        app: antifausa-net
    spec:
      containers:
      - name: antifausa-net
        image: cr.galenguyer.com/galenguyer.com:latest
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - antifausa-net
              topologyKey: "kubernetes.io/hostname"
            weight: 100
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antifausa-net
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  rules:
  - host: antifausa.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: antifausa-net
            port:
              number: 80
  tls:
  - hosts:
    - antifausa.net
    secretName: antifausa-net-cert
