---
apiVersion: v1
kind: Service
metadata:
  name: color
spec:
  type: ClusterIP
  selector:
    app: color
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000   

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
        - name: color
          image: cr.galenguyer.com/color
          args: ["gunicorn", "color:APP", "--access-logfile=-", "--bind=:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "color-redis"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - color
              topologyKey: "kubernetes.io/hostname"
            weight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: color-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: color-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-redis
  labels:
    name: color-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-redis
  template:
    metadata:
      labels:
        app: color-redis
        name: color-redis
    spec:
      containers:
        - name: color-redis
          image: redis
          volumeMounts:
            - name: vol
              mountPath: /data
          ports:
            - containerPort: 6379
              name: redis
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: color-redis-pvc
          
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: color-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-antifausa-net
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  rules:
  - host: color.antifausa.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: color
            port:
              number: 80
  tls:
  - hosts:
    - color.antifausa.net
    secretName: color-antifausa-net-cert
