apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: antifausa-net-cert
spec:
  secretName: antifausa-net-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
    rotationPolicy: Always
  dnsNames:
  - "antifausa.net"
  - "*.antifausa.net"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
